### ISSUE TITLE
Tutorial code does not work on 0.1.0, it relies on nursery.start_soon()

### ISSUE THREAD

**Issue by mpacer** [python-trio/trio#348]
With IPython 6.2.1 & Python 3.6.2 interpreters, if I attempt to use the code in

```python

# tasks-intro.py

import trio

async def child1():
    print("  child1: started! sleeping now...")
    await trio.sleep(1)
    print("  child1: exiting!")

async def child2():
    print("  child2: started! sleeping now...")
    await trio.sleep(1)
    print("  child2: exiting!")

async def parent():
    print("parent: started!")
    async with trio.open_nursery() as nursery:
        print("parent: spawning child1...")
        nursery.start_soon(child1)

        print("parent: spawning child2...")
        nursery.start_soon(child2)

        print("parent: waiting for children to finish...")
        # -- we exit the nursery block here --
    print("parent: all done!")

trio.run(parent)
```

It throws an error:

`AttributeError: 'Nursery' object has no attribute 'start_soon'`

I'm assuming this is because Nurseries cannot work in an interpreter… but it would be useful to know that this mode of debugging is no longer possible when learning this type of code. 

If you had such a warning, I didn't notice it. Which may fall on me; but it also might be helpful to remind people every time you introduce a function like this that it _needs_ to be run from a python file…

**Comment by mpacer** [comment]
Actually strike that… it also doesn't work if I run it from inside a file…. I'm really confused, I am pretty sure I have the latest version of trio…

**Comment by mpacer** [comment]
Ok… so it doesn't seem to work on the released version of trio, but it does work on master. That would be good to fix with a new release.

**Comment by njsmith** [comment]
Yeah, I really need to get a release out, sorry :-(

**Comment by njsmith** [comment]
0.2.0 is released!
